[install]
build = 20
install_source_checksum = c8518d36d3045c71eee14af6eb64063f1e82cc7d

[package]
id = twilio_alert
check_for_updates = 1

[ui]
is_visible = 1
label = Twilio SMS Alerting

[launcher]
author = BaboonBones Ltd
description = Modular Alert for sending SMS alerts using Twilio
version = 1.4.4
